# Generated by Django 2.2.28 on 2024-03-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240226_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
