# Generated by Django 2.2.28 on 2024-03-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240308_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
    ]
