# Generated by Django 2.2.28 on 2024-03-19 12:49

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240318_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to=app.models.user_filename),
        ),
    ]
