# Generated by Django 2.2.28 on 2024-03-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20240320_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='recurring',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurring_frequency',
        ),
    ]
